# -*- coding: utf-8 -*-
"""CrudeAnalyst.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6GWo3hxuLNcw9nZdlGHW8Zefv7ZbpIT
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import yfinance as yf
import requests

st.set_page_config(page_title="Crude Oil Analyst Dashboard", layout="wide")

# -----------------------------
# Sidebar
# -----------------------------
st.sidebar.header("Dashboard Controls")

benchmark = st.sidebar.selectbox(
    "Select Benchmark",
    ["CL=F (WTI)", "BZ=F (Brent)"]
)

period = st.sidebar.selectbox(
    "Select Time Period",
    ["1mo", "3mo", "6mo", "1y", "2y", "5y", "max"]
)

# -----------------------------
# Title
# -----------------------------
st.title("🛢️ Crude Oil Analyst Dashboard")
st.caption("A workspace for monitoring crude markets, fundamentals, and macro drivers.")

# -----------------------------
# Market Data Section
# -----------------------------
st.subheader("📈 Benchmark Price Overview")

ticker = yf.Ticker(benchmark)
hist = ticker.history(period=period)

fig = px.line(
    hist,
    x=hist.index,
    y="Close",
    title=f"{benchmark} Price Trend",
    labels={"Close": "Price (USD)", "index": "Date"}
)

st.plotly_chart(fig, use_container_width=True)

col1, col2, col3 = st.columns(3)
with col1:
    st.metric("Latest Price", f"${hist['Close'][-1]:.2f}")
with col2:
    st.metric("Daily Change", f"{hist['Close'][-1] - hist['Close'][-2]:.2f}")
with col3:
    pct = (hist['Close'][-1] / hist['Close'][0] - 1) * 100
    st.metric("Period Return", f"{pct:.2f}%")

# -----------------------------
# Supply & Demand Indicators
# -----------------------------
st.subheader("⚖️ Supply & Demand Indicators (Manual Inputs)")

colA, colB = st.columns(2)

with colA:
    opec_output = st.number_input("OPEC Output (mbpd)", value=28.0)
    us_production = st.number_input("US Production (mbpd)", value=13.2)
    inventory_level = st.number_input("OECD Inventories (mb)", value=2700)

with colB:
    refinery_runs = st.number_input("Global Refinery Runs (mbpd)", value=82.0)
    demand_growth = st.number_input("Demand Growth (mbpd)", value=1.5)
    spare_capacity = st.number_input("OPEC Spare Capacity (mbpd)", value=3.5)

st.success("Supply & demand inputs updated.")

# -----------------------------
# Crack Spread Calculator
# -----------------------------
st.subheader("🧮 Refining Margin (Crack Spread) Calculator")

colC, colD, colE = st.columns(3)

with colC:
    crude_price = st.number_input("Crude Price (USD/bbl)", value=80.0)
with colD:
    gasoline_price = st.number_input("Gasoline Price (USD/bbl)", value=95.0)
with colE:
    diesel_price = st.number_input("Diesel Price (USD/bbl)", value=100.0)

crack_spread = (0.5 * gasoline_price + 0.5 * diesel_price) - crude_price

st.metric("3-2-1 Crack Spread", f"${crack_spread:.2f}")

# -----------------------------
# News Feed
# -----------------------------
st.subheader("📰 Latest Oil Market News")

def get_news():
    url = "https://newsapi.org/v2/everything"
    params = {
        "q": "crude oil OR OPEC OR energy markets",
        "sortBy": "publishedAt",
        "language": "en",
        "apiKey": "YOUR_NEWS_API_KEY"
    }
    try:
        r = requests.get(url, params=params)
        data = r.json()
        return data.get("articles", [])
    except:
        return []

articles = get_news()

for a in articles[:5]:
    st.write(f"### {a['title']}")
    st.write(a['description'])
    st.write(f"[Read more]({a['url']})")
    st.write("---")